# 프로그램 실행 시 테이블 update
spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
    show-sql: true


# 로깅 설정
logging:
  level:
    org:
      springframework: ERROR
      hibernate:
        orm:
          jdbc:
            bind: trace
