spring:
  config:
    import: optional:file:src/main/resources/.env[.properties]
  profiles:
    active: dev
    group:
      dev: "dev, datasource"
      prod: "prod, datasource"

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


