services:
  spring-blue:
    image: spring-blue-image
    container_name: spring-blue-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - blue-green-network

  spring-green:
    image: spring-green-image
    container_name: spring-green-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - blue-green-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-blue
      - spring-green
    networks:
      - blue-green-network


networks:
  blue-green-network:
    driver: bridge