## Blue/Green 배포 스크립트

services:
  spring-blue:
    image: spring-blue-image
    container_name: spring-blue-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - shared-network

  spring-green:
    image: spring-green-image
    container_name: spring-green-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - shared-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8000:80"
    networks:
      - shared-network

networks:
  shared-network:
    name: pricewagon-network  # 고정된 네트워크 이름을 지정
    driver: bridge
    external: true  # 이미 존재하는 네트워크를 재사용하도록 설정