name: Pricewagon - BackEnd - CD

on:
  push:
    branches:
      - main
      -
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 프로젝트 저장소에 업로드하면 안되는 설정 파일들을 만들어줍니다.
      - name: Make application.yml
        run: |
          touch ./.env
          echo "$ENV" >./.env
        env:
          ENV: ${{ secrets.ENV }}
        shell: bash

      - name: Gradle 권한 부여
        run: chmod +x gradlew

      - name: Gradle로 빌드 실행
        run: ./gradlew bootjar

      # 배포에 필요한 여러 설정 파일과 프로젝트 빌드파일을 zip 파일로 모아줍니다.
      - name: zip file 생성
        run: |
          mkdir deploy
          cp ./docker/Dockerfile ./deploy/
          cp ./scripts/*.sh ./deploy/
          cp ./build/libs/*.jar ./deploy/
          chmod +x ./deploy/deploy.sh
          zip -r -qq -j ./pricewagon-back-app.zip ./deploy

      # zip 파일을 서버로 전송
      - name: Copy zip file to remote server
        run: scp -P ${{ secrets.SSH_PORT }} pricewagon-back-app.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/hong/app/

      # SSH 연결 후 프로젝트 업로드
      - name: Execute SSH command on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/hong/app
            unzip -o pricewagon-back-app.zip
            chmod +x ./deploy.sh
            ./scripts/deploy.sh